[2023-08-30T13:21:40.053+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: vnstock-pipeline-1M.Vm_pub_pubsub_1M scheduled__2023-08-30T01:00:00+00:00 [queued]>
[2023-08-30T13:21:40.058+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: vnstock-pipeline-1M.Vm_pub_pubsub_1M scheduled__2023-08-30T01:00:00+00:00 [queued]>
[2023-08-30T13:21:40.059+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 4
[2023-08-30T13:21:40.074+0000] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): Vm_pub_pubsub_1M> on 2023-08-30 01:00:00+00:00
[2023-08-30T13:21:40.079+0000] {clientserver.py:543} INFO - Closing down clientserver connection
[2023-08-30T13:21:40.079+0000] {standard_task_runner.py:57} INFO - Started process 365889 to run task
[2023-08-30T13:21:40.087+0000] {standard_task_runner.py:84} INFO - Running: ['airflow', 'tasks', 'run', 'vnstock-pipeline-1M', 'Vm_pub_pubsub_1M', 'scheduled__2023-08-30T01:00:00+00:00', '--job-id', '251', '--raw', '--subdir', 'DAGS_FOLDER/main.py', '--cfg-path', '/tmp/tmpt4wecid3']
[2023-08-30T13:21:40.087+0000] {standard_task_runner.py:85} INFO - Job 251: Subtask Vm_pub_pubsub_1M
[2023-08-30T13:21:40.128+0000] {task_command.py:415} INFO - Running <TaskInstance: vnstock-pipeline-1M.Vm_pub_pubsub_1M scheduled__2023-08-30T01:00:00+00:00 [running]> on host vnstock-pipeline-vm.us-central1-c.c.vnstock-pipeline.internal
[2023-08-30T13:21:40.176+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='nguyentuanduong555@gmail.com' AIRFLOW_CTX_DAG_OWNER='Duong_' AIRFLOW_CTX_DAG_ID='vnstock-pipeline-1M' AIRFLOW_CTX_TASK_ID='Vm_pub_pubsub_1M' AIRFLOW_CTX_EXECUTION_DATE='2023-08-30T01:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-08-30T01:00:00+00:00'
[2023-08-30T13:21:40.219+0000] {clientserver.py:505} INFO - Error while sending or receiving.
Traceback (most recent call last):
  File "/home/nguyentuanduong7/.local/lib/python3.8/site-packages/py4j/clientserver.py", line 503, in send_command
    self.socket.sendall(command.encode("utf-8"))
ConnectionResetError: [Errno 104] Connection reset by peer
[2023-08-30T13:21:40.220+0000] {clientserver.py:543} INFO - Closing down clientserver connection
[2023-08-30T13:21:40.220+0000] {java_gateway.py:1052} INFO - Exception while sending command.
Traceback (most recent call last):
  File "/home/nguyentuanduong7/.local/lib/python3.8/site-packages/py4j/clientserver.py", line 503, in send_command
    self.socket.sendall(command.encode("utf-8"))
ConnectionResetError: [Errno 104] Connection reset by peer

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/nguyentuanduong7/.local/lib/python3.8/site-packages/py4j/java_gateway.py", line 1038, in send_command
    response = connection.send_command(command)
  File "/home/nguyentuanduong7/.local/lib/python3.8/site-packages/py4j/clientserver.py", line 506, in send_command
    raise Py4JNetworkError(
py4j.protocol.Py4JNetworkError: Error while sending
[2023-08-30T13:21:40.223+0000] {clientserver.py:543} INFO - Closing down clientserver connection
[2023-08-30T13:21:40.749+0000] {logging_mixin.py:151} INFO - Ticker         ACB
Matched    22450.0
[2023-08-30T13:21:41.355+0000] {logging_mixin.py:151} INFO - Ticker         TCB
Matched    34000.0
[2023-08-30T13:21:41.356+0000] {python.py:194} INFO - Done. Returned value was: None
[2023-08-30T13:21:41.360+0000] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=vnstock-pipeline-1M, task_id=Vm_pub_pubsub_1M, execution_date=20230830T010000, start_date=20230830T132140, end_date=20230830T132141
[2023-08-30T13:21:41.379+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 0
[2023-08-30T13:21:41.390+0000] {taskinstance.py:2784} INFO - 0 downstream tasks scheduled from follow-on schedule check
