[2023-08-24T04:26:55.177+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: vnstock-pipeline.Vm_pub_pubsub manual__2023-08-24T04:26:33.363611+00:00 [queued]>
[2023-08-24T04:26:55.181+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: vnstock-pipeline.Vm_pub_pubsub manual__2023-08-24T04:26:33.363611+00:00 [queued]>
[2023-08-24T04:26:55.182+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 4
[2023-08-24T04:26:55.194+0000] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): Vm_pub_pubsub> on 2023-08-24 04:26:33.363611+00:00
[2023-08-24T04:26:55.197+0000] {standard_task_runner.py:57} INFO - Started process 39688 to run task
[2023-08-24T04:26:55.198+0000] {clientserver.py:543} INFO - Closing down clientserver connection
[2023-08-24T04:26:55.205+0000] {standard_task_runner.py:84} INFO - Running: ['airflow', 'tasks', 'run', 'vnstock-pipeline', 'Vm_pub_pubsub', 'manual__2023-08-24T04:26:33.363611+00:00', '--job-id', '115', '--raw', '--subdir', 'DAGS_FOLDER/main.py', '--cfg-path', '/tmp/tmp6958g8_q']
[2023-08-24T04:26:55.205+0000] {standard_task_runner.py:85} INFO - Job 115: Subtask Vm_pub_pubsub
[2023-08-24T04:26:55.241+0000] {task_command.py:415} INFO - Running <TaskInstance: vnstock-pipeline.Vm_pub_pubsub manual__2023-08-24T04:26:33.363611+00:00 [running]> on host vnstock-pipeline-vm.us-central1-c.c.vnstock-pipeline.internal
[2023-08-24T04:26:55.266+0000] {clientserver.py:505} INFO - Error while sending or receiving.
Traceback (most recent call last):
  File "/home/nguyentuanduong7/.local/lib/python3.8/site-packages/py4j/clientserver.py", line 503, in send_command
    self.socket.sendall(command.encode("utf-8"))
ConnectionResetError: [Errno 104] Connection reset by peer
[2023-08-24T04:26:55.267+0000] {clientserver.py:543} INFO - Closing down clientserver connection
[2023-08-24T04:26:55.268+0000] {java_gateway.py:1052} INFO - Exception while sending command.
Traceback (most recent call last):
  File "/home/nguyentuanduong7/.local/lib/python3.8/site-packages/py4j/clientserver.py", line 503, in send_command
    self.socket.sendall(command.encode("utf-8"))
ConnectionResetError: [Errno 104] Connection reset by peer

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/nguyentuanduong7/.local/lib/python3.8/site-packages/py4j/java_gateway.py", line 1038, in send_command
    response = connection.send_command(command)
  File "/home/nguyentuanduong7/.local/lib/python3.8/site-packages/py4j/clientserver.py", line 506, in send_command
    raise Py4JNetworkError(
py4j.protocol.Py4JNetworkError: Error while sending
[2023-08-24T04:26:55.271+0000] {clientserver.py:543} INFO - Closing down clientserver connection
[2023-08-24T04:26:55.294+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='nguyentuanduong555@gmail.com' AIRFLOW_CTX_DAG_OWNER='Duong' AIRFLOW_CTX_DAG_ID='vnstock-pipeline' AIRFLOW_CTX_TASK_ID='Vm_pub_pubsub' AIRFLOW_CTX_EXECUTION_DATE='2023-08-24T04:26:33.363611+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-08-24T04:26:33.363611+00:00'
[2023-08-24T04:26:56.279+0000] {logging_mixin.py:151} INFO - publish message id 8792949197428849
[2023-08-24T04:26:56.321+0000] {logging_mixin.py:151} INFO - publish message id 8272965045972256
[2023-08-24T04:26:56.321+0000] {python.py:194} INFO - Done. Returned value was: None
[2023-08-24T04:26:56.325+0000] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=vnstock-pipeline, task_id=Vm_pub_pubsub, execution_date=20230824T042633, start_date=20230824T042655, end_date=20230824T042656
[2023-08-24T04:26:56.376+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 0
[2023-08-24T04:26:56.387+0000] {taskinstance.py:2784} INFO - 0 downstream tasks scheduled from follow-on schedule check
