[2023-08-29T13:25:01.874+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: vnstock-pipeline-1H.Vm_pub_pubsub manual__2023-08-29T13:22:20.405001+00:00 [queued]>
[2023-08-29T13:25:01.879+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: vnstock-pipeline-1H.Vm_pub_pubsub manual__2023-08-29T13:22:20.405001+00:00 [queued]>
[2023-08-29T13:25:01.879+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 4
[2023-08-29T13:25:01.895+0000] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): Vm_pub_pubsub> on 2023-08-29 13:22:20.405001+00:00
[2023-08-29T13:25:01.899+0000] {standard_task_runner.py:57} INFO - Started process 166957 to run task
[2023-08-29T13:25:01.899+0000] {clientserver.py:543} INFO - Closing down clientserver connection
[2023-08-29T13:25:01.905+0000] {standard_task_runner.py:84} INFO - Running: ['airflow', 'tasks', 'run', 'vnstock-pipeline-1H', 'Vm_pub_pubsub', 'manual__2023-08-29T13:22:20.405001+00:00', '--job-id', '136', '--raw', '--subdir', 'DAGS_FOLDER/main.py', '--cfg-path', '/tmp/tmpeeu6osx2']
[2023-08-29T13:25:01.905+0000] {standard_task_runner.py:85} INFO - Job 136: Subtask Vm_pub_pubsub
[2023-08-29T13:25:01.946+0000] {task_command.py:415} INFO - Running <TaskInstance: vnstock-pipeline-1H.Vm_pub_pubsub manual__2023-08-29T13:22:20.405001+00:00 [running]> on host vnstock-pipeline-vm.us-central1-c.c.vnstock-pipeline.internal
[2023-08-29T13:25:01.967+0000] {clientserver.py:505} INFO - Error while sending or receiving.
Traceback (most recent call last):
  File "/home/nguyentuanduong7/.local/lib/python3.8/site-packages/py4j/clientserver.py", line 503, in send_command
    self.socket.sendall(command.encode("utf-8"))
ConnectionResetError: [Errno 104] Connection reset by peer
[2023-08-29T13:25:01.969+0000] {clientserver.py:543} INFO - Closing down clientserver connection
[2023-08-29T13:25:01.970+0000] {java_gateway.py:1052} INFO - Exception while sending command.
Traceback (most recent call last):
  File "/home/nguyentuanduong7/.local/lib/python3.8/site-packages/py4j/clientserver.py", line 503, in send_command
    self.socket.sendall(command.encode("utf-8"))
ConnectionResetError: [Errno 104] Connection reset by peer

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/nguyentuanduong7/.local/lib/python3.8/site-packages/py4j/java_gateway.py", line 1038, in send_command
    response = connection.send_command(command)
  File "/home/nguyentuanduong7/.local/lib/python3.8/site-packages/py4j/clientserver.py", line 506, in send_command
    raise Py4JNetworkError(
py4j.protocol.Py4JNetworkError: Error while sending
[2023-08-29T13:25:01.976+0000] {clientserver.py:543} INFO - Closing down clientserver connection
[2023-08-29T13:25:01.994+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='nguyentuanduong555@gmail.com' AIRFLOW_CTX_DAG_OWNER='Duong' AIRFLOW_CTX_DAG_ID='vnstock-pipeline-1H' AIRFLOW_CTX_TASK_ID='Vm_pub_pubsub' AIRFLOW_CTX_EXECUTION_DATE='2023-08-29T13:22:20.405001+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-08-29T13:22:20.405001+00:00'
[2023-08-29T13:25:03.073+0000] {logging_mixin.py:151} INFO - publish message id 8306533191569391
[2023-08-29T13:25:03.225+0000] {logging_mixin.py:151} INFO - publish message id 9405913965008314
[2023-08-29T13:25:03.226+0000] {python.py:194} INFO - Done. Returned value was: None
[2023-08-29T13:25:03.230+0000] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=vnstock-pipeline-1H, task_id=Vm_pub_pubsub, execution_date=20230829T132220, start_date=20230829T132501, end_date=20230829T132503
[2023-08-29T13:25:03.280+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 0
[2023-08-29T13:25:03.291+0000] {taskinstance.py:2784} INFO - 0 downstream tasks scheduled from follow-on schedule check
