[2023-08-24T03:33:36.038+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: vnstock-pipeline.Vm_pubsub_3M manual__2023-08-23T11:01:03.194505+00:00 [queued]>
[2023-08-24T03:33:36.043+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: vnstock-pipeline.Vm_pubsub_3M manual__2023-08-23T11:01:03.194505+00:00 [queued]>
[2023-08-24T03:33:36.043+0000] {taskinstance.py:1361} INFO - Starting attempt 9 of 4
[2023-08-24T03:33:36.056+0000] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): Vm_pubsub_3M> on 2023-08-23 11:01:03.194505+00:00
[2023-08-24T03:33:36.060+0000] {standard_task_runner.py:57} INFO - Started process 26870 to run task
[2023-08-24T03:33:36.060+0000] {clientserver.py:543} INFO - Closing down clientserver connection
[2023-08-24T03:33:36.067+0000] {standard_task_runner.py:84} INFO - Running: ['airflow', 'tasks', 'run', 'vnstock-pipeline', 'Vm_pubsub_3M', 'manual__2023-08-23T11:01:03.194505+00:00', '--job-id', '54', '--raw', '--subdir', 'DAGS_FOLDER/main.py', '--cfg-path', '/tmp/tmpsw6mqv5i']
[2023-08-24T03:33:36.067+0000] {standard_task_runner.py:85} INFO - Job 54: Subtask Vm_pubsub_3M
[2023-08-24T03:33:36.101+0000] {task_command.py:415} INFO - Running <TaskInstance: vnstock-pipeline.Vm_pubsub_3M manual__2023-08-23T11:01:03.194505+00:00 [running]> on host vnstock-pipeline-vm.us-central1-c.c.vnstock-pipeline.internal
[2023-08-24T03:33:36.135+0000] {clientserver.py:505} INFO - Error while sending or receiving.
Traceback (most recent call last):
  File "/home/nguyentuanduong7/.local/lib/python3.8/site-packages/py4j/clientserver.py", line 503, in send_command
    self.socket.sendall(command.encode("utf-8"))
ConnectionResetError: [Errno 104] Connection reset by peer
[2023-08-24T03:33:36.136+0000] {clientserver.py:543} INFO - Closing down clientserver connection
[2023-08-24T03:33:36.136+0000] {java_gateway.py:1052} INFO - Exception while sending command.
Traceback (most recent call last):
  File "/home/nguyentuanduong7/.local/lib/python3.8/site-packages/py4j/clientserver.py", line 503, in send_command
    self.socket.sendall(command.encode("utf-8"))
ConnectionResetError: [Errno 104] Connection reset by peer

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/nguyentuanduong7/.local/lib/python3.8/site-packages/py4j/java_gateway.py", line 1038, in send_command
    response = connection.send_command(command)
  File "/home/nguyentuanduong7/.local/lib/python3.8/site-packages/py4j/clientserver.py", line 506, in send_command
    raise Py4JNetworkError(
py4j.protocol.Py4JNetworkError: Error while sending
[2023-08-24T03:33:36.143+0000] {clientserver.py:543} INFO - Closing down clientserver connection
[2023-08-24T03:33:36.150+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='nguyentuanduong555@gmail.com' AIRFLOW_CTX_DAG_OWNER='Duong' AIRFLOW_CTX_DAG_ID='vnstock-pipeline' AIRFLOW_CTX_TASK_ID='Vm_pubsub_3M' AIRFLOW_CTX_EXECUTION_DATE='2023-08-23T11:01:03.194505+00:00' AIRFLOW_CTX_TRY_NUMBER='9' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-08-23T11:01:03.194505+00:00'
[2023-08-24T03:33:41.290+0000] {logging_mixin.py:151} INFO - root
 |-- Time: timestamp (nullable = true)
 |-- Ticker: string (nullable = true)
 |-- Close: double (nullable = true)
 |-- Percentage_Change: double (nullable = true)
